import type { Metadata } from 'next'
import { ControlNav } from '@/components/control/ControlNav'
import { requireAdmin } from '@/lib/auth'
import { createNewProjectAction } from '../actions'
import { NewProjectForm } from '../_components/NewProjectForm'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Add New Project' }

type PageProps = { searchParams?: Promise<{ error?: string }> }

export default async function NewProjectCreatePage({ searchParams }: PageProps) {
  await requireAdmin()
  const params = (await searchParams) || {}
  return (
    <section className="dashboard-shell admin-shell">
      <ControlNav />
      <div className="dashboard-main">
        <div className="dashboard-hero admin-hero"><p className="eyebrow">Create project</p><h1>Add a new estate project.</h1><p>Projects save as draft unless published explicitly. A stable NP reference is generated by the backend.</p></div>
        <NewProjectForm action={createNewProjectAction} submitLabel="Create Project" error={params.error} />
      </div>
    </section>
  )
}
