create table if not exists profiles (
  id char(36) primary key default (uuid()),
  user_id char(36) not null unique,
  full_name varchar(255),
  email varchar(255),
  phone varchar(64),
  whatsapp varchar(64),
  country varchar(120),
  primary_role enum(
    'user',
    'buyer',
    'tenant',
    'investor',
    'owner',
    'landlord',
    'developer',
    'agent',
    'property_manager',
    'representative',
    'corporate_client',
    'family_office',
    'admin',
    'compliance',
    'super_admin'
  ) not null default 'user',
  verification_level varchar(80) not null default 'unverified',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  index profiles_user_id_idx (user_id),
  index profiles_primary_role_idx (primary_role)
);

create table if not exists user_roles (
  id char(36) primary key default (uuid()),
  user_id char(36) not null,
  role enum(
    'user',
    'buyer',
    'tenant',
    'investor',
    'owner',
    'landlord',
    'developer',
    'agent',
    'property_manager',
    'representative',
    'corporate_client',
    'family_office',
    'admin',
    'compliance',
    'super_admin'
  ) not null,
  assigned_by char(36),
  created_at timestamp not null default current_timestamp,
  unique key user_roles_user_role_unique (user_id, role),
  index user_roles_user_role_idx (user_id, role),
  constraint user_roles_profile_fk foreign key (user_id) references profiles(user_id) on delete cascade
);

create table if not exists interest_signals (
  id char(36) primary key default (uuid()),
  user_id varchar(128) not null,
  title varchar(255) not null,
  reference_code varchar(32) not null,
  user_role enum(
    'Buyer',
    'Investor',
    'Developer',
    'agent',
    'Property manager',
    'Corporate client',
    'Admin'
  ) not null,
  availability_type enum(
    'May rent privately',
    'Upcoming vacancy',
    'May sell privately',
    'Developer inventory',
    'Land opportunity',
    'Commercial opportunity',
    'Verified listing request',
    'Private matching only'
  ) not null,
  listing_intent enum(
    'Keep private - match only',
    'Request verified private listing',
    'Request public listing after compliance approval',
    'Deal room reveal only'
  ) not null,
  market_segment enum(
    'Residential',
    'Commercial',
    'Off-plan',
    'Secondary',
    'Land',
    'Industrial',
    'Hospitality',
    'Investment',
    'Special purpose',
    'Other'
  ) not null,
  property_type enum(
    'Apartment / flat',
    'Studio apartment',
    'Serviced apartment',
    'Villa',
    'Townhouse',
    'Duplex',
    'Penthouse',
    'Mansion / luxury home',
    'Residential building',
    'Whole building / bulk units',
    'Land / development plot',
    'Residential land',
    'Commercial land',
    'Agricultural land',
    'Industrial land',
    'Mixed-use land',
    'Office',
    'Retail shop',
    'Showroom',
    'Warehouse',
    'Industrial unit',
    'Labour camp / staff accommodation',
    'Camp',
    'Commercial building',
    'Hotel / hospitality',
    'Restaurant / F&B space',
    'Clinic / medical space',
    'Farmhouse / rural property',
    'Short-term rental opportunity',
    'Off-plan unit',
    'New development unit',
    'Branded residence',
    'Investment property',
    'Other / bespoke requirement'
  ) not null,
  country varchar(100) not null,
  area_city varchar(100) not null,
  project_name varchar(255),
  building_name varchar(255),
  size_sqft decimal(12,2) not null,
  price_min decimal(15,2) not null,
  price_max decimal(15,2) not null,
  availability_date date not null,
  privacy_level enum(
    'Admin only',
    'Matched users only',
    'Deal room only',
    'Public advertising only with permit'
  ) not null,
  private_description text not null,
  category enum('residential', 'commercial') not null,
  offering_type enum('rent', 'sell') not null,
  rooms int not null,
  bedrooms int not null,
  total_floors int not null,
  parking_spaces int not null,
  furnishing_type enum('unfurnished', 'semi-furnished', 'Furnished') not null,
  project_status enum('resale', 'ready to move', 'on plan', 'under construction') not null,
  amenities json not null,
  preferred_payment_method enum('Cash', 'Crypto', 'Installments') not null,
  approval_status enum(
    'pending_review',
    'documents_requested',
    'under_verification',
    'compliance_hold',
    'approved',
    'rejected',
    'archived'
  ) not null default 'pending_review',
  public_status enum('hidden', 'open', 'matching', 'matched', 'archived') not null default 'hidden',
  verification_status enum(
    'unverified',
    'basic_checked',
    'documents_submitted',
    'under_review',
    'verified',
    'failed',
    'expired'
  ) not null default 'unverified',
  verified_at timestamp null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  constraint interest_signals_size_nonnegative check (size_sqft >= 0),
  constraint interest_signals_price_min_nonnegative check (price_min >= 0),
  constraint interest_signals_price_max_nonnegative check (price_max >= 0),
  constraint interest_signals_price_order check (price_max >= price_min),
  constraint interest_signals_rooms_nonnegative check (rooms >= 0),
  constraint interest_signals_bedrooms_nonnegative check (bedrooms >= 0),
  constraint interest_signals_total_floors_nonnegative check (total_floors >= 0),
  constraint interest_signals_parking_spaces_nonnegative check (parking_spaces >= 0),
  constraint interest_signals_amenities_array check (json_type(amenities) = 'ARRAY'),
  unique key interest_signals_reference_code_unique (reference_code),
  index interest_signals_user_idx (user_id),
  index interest_signals_status_idx (approval_status, public_status, verification_status),
  index interest_signals_payment_idx (preferred_payment_method),
  index interest_signals_match_idx (country, area_city, category, offering_type, property_type, market_segment)
);

create table if not exists private_availability (
  id char(36) primary key default (uuid()),
  user_id varchar(128) not null,
  title varchar(255) not null,
  user_role enum(
    'Direct owner',
    'Direct landlord',
    'Developer',
    'Licensed agent with authority',
    'Property manager with authority',
    'Representative with written mandate'
  ) not null,
  availability_type enum(
    'May rent privately',
    'Upcoming vacancy',
    'May sell privately',
    'Developer inventory',
    'Land opportunity',
    'Commercial opportunity',
    'Verified listing request',
    'Private matching only'
  ) not null,
  listing_intent enum(
    'Keep private - match only',
    'Request verified private listing',
    'Request public listing after compliance approval',
    'Deal room reveal only'
  ) not null,
  market_segment enum(
    'Residential',
    'Commercial',
    'Off-plan',
    'Secondary',
    'Land',
    'Industrial',
    'Hospitality',
    'Investment',
    'Special purpose',
    'Other'
  ) not null,
  property_type enum(
    'Apartment / flat',
    'Studio apartment',
    'Serviced apartment',
    'Villa',
    'Townhouse',
    'Duplex',
    'Penthouse',
    'Mansion / luxury home',
    'Residential building',
    'Whole building / bulk units',
    'Land / development plot',
    'Residential land',
    'Commercial land',
    'Agricultural land',
    'Industrial land',
    'Mixed-use land',
    'Office',
    'Retail shop',
    'Showroom',
    'Warehouse',
    'Industrial unit',
    'Labour camp / staff accommodation',
    'Camp',
    'Commercial building',
    'Hotel / hospitality',
    'Restaurant / F&B space',
    'Clinic / medical space',
    'Farmhouse / rural property',
    'Short-term rental opportunity',
    'Off-plan unit',
    'New development unit',
    'Branded residence',
    'Investment property',
    'Other / bespoke requirement'
  ) not null,
  country varchar(100) not null,
  area_city varchar(100) not null,
  project_name varchar(255),
  building_name varchar(255),
  size_sqft decimal(12,2) not null,
  price_min decimal(15,2) not null,
  price_max decimal(15,2) not null,
  availability_date date not null,
  privacy_level enum(
    'Admin only',
    'Matched users only',
    'Deal room only',
    'Public advertising only with permit'
  ) not null,
  authority_declaration enum(
    'I am the direct owner/landlord',
    'I have written authority',
    'I represent a developer',
    'I am a licensed agent and will upload proof later'
  ) not null,
  private_description text not null,
  category enum('residential', 'commercial') not null,
  offering_type enum('rent', 'sell') not null,
  rooms int not null,
  bedrooms int not null,
  total_floors int not null,
  parking_spaces int not null,
  furnishing_type enum('unfurnished', 'semi-furnished', 'Furnished') not null,
  project_status enum('resale', 'ready to move', 'on plan', 'under construction') not null,
  amenities json not null,
  preferred_payment_method enum('Cash', 'Crypto', 'Installments') not null,
  has_verification_files_attached boolean not null default false,
  approval_status enum(
    'pending_review',
    'documents_requested',
    'under_verification',
    'compliance_hold',
    'approved',
    'rejected',
    'archived'
  ) not null default 'pending_review',
  public_status enum('hidden', 'open', 'matching', 'matched', 'archived') not null default 'hidden',
  verification_status enum(
    'unverified',
    'basic_checked',
    'documents_submitted',
    'under_review',
    'verified',
    'failed',
    'expired'
  ) not null default 'unverified',
  verified_at timestamp null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  constraint private_availability_size_nonnegative check (size_sqft >= 0),
  constraint private_availability_price_min_nonnegative check (price_min >= 0),
  constraint private_availability_price_max_nonnegative check (price_max >= 0),
  constraint private_availability_price_order check (price_max >= price_min),
  constraint private_availability_rooms_nonnegative check (rooms >= 0),
  constraint private_availability_bedrooms_nonnegative check (bedrooms >= 0),
  constraint private_availability_total_floors_nonnegative check (total_floors >= 0),
  constraint private_availability_parking_spaces_nonnegative check (parking_spaces >= 0),
  constraint private_availability_amenities_array check (json_type(amenities) = 'ARRAY'),
  index private_availability_user_idx (user_id),
  index private_availability_status_idx (approval_status, public_status, verification_status),
  index private_availability_payment_idx (preferred_payment_method, has_verification_files_attached),
  index private_availability_match_idx (country, area_city, category, offering_type, property_type, market_segment)
);

create table if not exists verified_listing_requests (
  id char(36) primary key default (uuid()),
  user_id char(36),
  contact_name varchar(255),
  contact_email varchar(255),
  contact_phone varchar(64),
  submitter_role varchar(80),
  country varchar(120),
  area_city varchar(180),
  project_name varchar(255),
  building_name varchar(255),
  property_category varchar(120),
  property_type varchar(120),
  market_segment varchar(120),
  purpose varchar(120),
  size_label varchar(120),
  bedrooms int,
  bathrooms int,
  price_label varchar(120),
  currency varchar(20),
  availability_date date,
  ownership_status varchar(120),
  permit_status varchar(120),
  privacy_level varchar(120),
  description text,
  approval_status varchar(40) not null default 'pending_review',
  public_status varchar(40) not null default 'hidden',
  verification_status varchar(40) not null default 'documents_submitted',
  verified_by char(36),
  verified_at timestamp null,
  uploaded_documents json not null,
  form_data json not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  index verified_status_idx (approval_status, public_status, verification_status),
  index verified_user_idx (user_id)
);

create table if not exists investor_posts (
  id char(36) primary key default (uuid()),
  user_id char(36),
  contact_name varchar(255),
  contact_email varchar(255),
  contact_phone varchar(64),
  investor_type varchar(120),
  investment_goal varchar(120),
  countries json,
  area_city varchar(180),
  property_categories json,
  property_types json,
  market_segments json,
  ticket_label varchar(120),
  currency varchar(20),
  budget_visibility varchar(120),
  target_yield varchar(120),
  risk_preference varchar(120),
  timeline varchar(120),
  holding_period varchar(120),
  exit_strategy varchar(120),
  description text,
  accepts_direct_owner boolean not null default false,
  accepts_developer boolean not null default false,
  accepts_agent boolean not null default false,
  approval_status varchar(40) not null default 'pending_review',
  public_status varchar(40) not null default 'hidden',
  verification_status varchar(40) not null default 'unverified',
  form_data json not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  index investor_status_idx (approval_status, public_status, verification_status),
  index investor_user_idx (user_id)
);

create table if not exists agent_profiles (
  id char(36) primary key default (uuid()),
  user_id char(36),
  full_name varchar(255),
  email varchar(255),
  phone varchar(64),
  company_name varchar(255),
  country varchar(120),
  licence_number varchar(120),
  licence_expiry date,
  represents varchar(255),
  authority_status varchar(120),
  approval_status varchar(40) not null default 'pending_review',
  public_status varchar(40) not null default 'hidden',
  verification_status varchar(40) not null default 'unverified',
  form_data json not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  index agent_status_idx (approval_status, public_status, verification_status),
  index agent_user_idx (user_id)
);

create table if not exists newsletter_subscribers (
  id char(36) primary key default (uuid()),
  email varchar(255) not null unique,
  full_name varchar(255),
  segment varchar(120),
  status varchar(40) not null default 'subscribed',
  form_data json not null,
  created_at timestamp not null default current_timestamp
);

create table if not exists document_uploads (
  id char(36) primary key default (uuid()),
  owner_user_id char(36),
  related_object_type varchar(80) not null,
  related_object_id char(36) not null,
  document_type varchar(120) not null,
  storage_bucket varchar(120) not null,
  storage_path varchar(500) not null,
  original_filename varchar(255),
  mime_type varchar(120),
  file_size bigint,
  expiry_date date,
  verification_status varchar(40) not null default 'under_review',
  verified_by char(36),
  verified_at timestamp null,
  rejection_reason text,
  created_at timestamp not null default current_timestamp,
  index document_related_idx (related_object_type, related_object_id),
  index document_owner_idx (owner_user_id)
);

create table if not exists admin_actions (
  id char(36) primary key default (uuid()),
  admin_user_id char(36),
  admin_email varchar(255),
  action_type varchar(120) not null,
  object_type varchar(80) not null,
  object_id char(36) not null,
  previous_status varchar(80),
  new_status varchar(80),
  note text,
  ip_address varchar(80),
  created_at timestamp not null default current_timestamp,
  index admin_actions_object_idx (object_type, object_id, created_at)
);

create table if not exists compliance_checks (
  id char(36) primary key default (uuid()),
  object_type varchar(80) not null,
  object_id char(36) not null,
  check_type varchar(120) not null,
  status varchar(40) not null default 'pending',
  assigned_to char(36),
  notes text,
  completed_by char(36),
  completed_at timestamp null,
  created_at timestamp not null default current_timestamp,
  index compliance_object_idx (object_type, object_id)
);

create table if not exists match_requests (
  id char(36) primary key default (uuid()),
  source_object_type varchar(80) not null,
  source_object_id char(36) not null,
  target_object_type varchar(80) not null,
  target_object_id char(36) not null,
  match_score decimal(8,2),
  match_reason text,
  requested_by char(36),
  status varchar(40) not null default 'pending',
  admin_status varchar(40) not null default 'pending_review',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  index match_requested_by_idx (requested_by),
  unique key match_request_pair_unique (source_object_type, source_object_id, target_object_type, target_object_id)
);

create table if not exists match_rooms (
  id char(36) primary key default (uuid()),
  match_request_id char(36),
  status varchar(60) not null default 'pending_participant_approval',
  opened_by char(36),
  opened_at timestamp null,
  contact_unlocked boolean not null default false,
  documents_unlocked boolean not null default false,
  current_stage varchar(80) not null default 'intro',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  unique key match_rooms_request_unique (match_request_id),
  constraint match_rooms_request_fk foreign key (match_request_id) references match_requests(id) on delete cascade
);

create table if not exists match_room_participants (
  id char(36) primary key default (uuid()),
  match_room_id char(36) not null,
  user_id char(36) not null,
  role_in_room varchar(80) not null,
  approval_status varchar(40) not null default 'pending',
  contact_unlock_approved boolean not null default false,
  contact_unlock_approved_at timestamp null,
  approved_at timestamp null,
  created_at timestamp not null default current_timestamp,
  unique key match_room_participant_unique (match_room_id, user_id),
  constraint participants_room_fk foreign key (match_room_id) references match_rooms(id) on delete cascade
);

create table if not exists taxonomy_items (
  id char(36) primary key default (uuid()),
  taxonomy_type varchar(120) not null,
  label varchar(255) not null,
  slug varchar(255) not null,
  parent_id char(36),
  country_scope varchar(120),
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  unique key taxonomy_unique_scope_idx (taxonomy_type, slug, country_scope),
  index taxonomy_lookup_idx (taxonomy_type, country_scope, is_active, sort_order),
  constraint taxonomy_parent_fk foreign key (parent_id) references taxonomy_items(id) on delete set null
);

create table if not exists notifications (
  id char(36) primary key default (uuid()),
  user_id char(36),
  notification_type enum('submission_received', 'admin_alert_new_post', 'submission_approved', 'documents_requested', 'compliance_hold', 'match_proposed', 'match_room_opened', 'match_completed') not null,
  channel enum('email', 'in_app', 'push') not null default 'email',
  subject varchar(255) not null,
  body text not null,
  status enum('pending', 'sent', 'failed') not null default 'pending',
  sent_at timestamp null,
  provider_message_id varchar(255),
  error_message varchar(500),
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  created_at timestamp not null default current_timestamp,
  index notifications_user_idx (user_id, status, created_at),
  index notifications_type_status_idx (notification_type, status, created_at),
  constraint notifications_user_fk foreign key (user_id) references profiles(user_id) on delete set null
);

insert into profiles (user_id, full_name, email, primary_role, verification_level)
values
  ('00000000-0000-0000-0000-000000000001', 'Test Super Admin', 'admin@galaxy.test', 'super_admin', 'verified'),
  ('00000000-0000-0000-0000-000000000002', 'Test Buyer', 'buyer@galaxy.test', 'buyer', 'unverified')
on duplicate key update email = values(email), primary_role = values(primary_role), verification_level = values(verification_level);

insert into user_roles (user_id, role)
values
  ('00000000-0000-0000-0000-000000000001', 'user'),
  ('00000000-0000-0000-0000-000000000001', 'super_admin'),
  ('00000000-0000-0000-0000-000000000002', 'user'),
  ('00000000-0000-0000-0000-000000000002', 'buyer')
on duplicate key update role = values(role);
