create table if not exists private_availability (
  id char(36) primary key default (uuid()),
  user_id varchar(128) not null,
  title varchar(255) not null,
  user_role enum(
    'Direct owner',
    'Direct landlord',
    'Developer',
    'Licensed agent with authority',
    'Property manager with authority',
    'Representative with written mandate'
  ) not null,
  availability_type enum(
    'May rent privately',
    'Upcoming vacancy',
    'May sell privately',
    'Developer inventory',
    'Land opportunity',
    'Commercial opportunity',
    'Verified listing request',
    'Private matching only'
  ) not null,
  listing_intent enum(
    'Keep private - match only',
    'Request verified private listing',
    'Request public listing after compliance approval',
    'Deal room reveal only'
  ) not null,
  market_segment enum(
    'Residential',
    'Commercial',
    'Off-plan',
    'Secondary',
    'Land',
    'Industrial',
    'Hospitality',
    'Investment',
    'Special purpose',
    'Other'
  ) not null,
  property_type enum(
    'Apartment / flat',
    'Studio apartment',
    'Serviced apartment',
    'Villa',
    'Townhouse',
    'Duplex',
    'Penthouse',
    'Mansion / luxury home',
    'Residential building',
    'Whole building / bulk units',
    'Land / development plot',
    'Residential land',
    'Commercial land',
    'Agricultural land',
    'Industrial land',
    'Mixed-use land',
    'Office',
    'Retail shop',
    'Showroom',
    'Warehouse',
    'Industrial unit',
    'Labour camp / staff accommodation',
    'Camp',
    'Commercial building',
    'Hotel / hospitality',
    'Restaurant / F&B space',
    'Clinic / medical space',
    'Farmhouse / rural property',
    'Short-term rental opportunity',
    'Off-plan unit',
    'New development unit',
    'Branded residence',
    'Investment property',
    'Other / bespoke requirement'
  ) not null,
  country varchar(100) not null,
  area_city varchar(100) not null,
  project_name varchar(255),
  building_name varchar(255),
  size_sqft decimal(12,2) not null,
  price_min decimal(15,2) not null,
  price_max decimal(15,2) not null,
  availability_date date not null,
  privacy_level enum(
    'Admin only',
    'Matched users only',
    'Deal room only',
    'Public advertising only with permit'
  ) not null,
  authority_declaration enum(
    'I am the direct owner/landlord',
    'I have written authority',
    'I represent a developer',
    'I am a licensed agent and will upload proof later'
  ) not null,
  private_description text not null,
  category enum('residential', 'commercial') not null,
  offering_type enum('rent', 'sell') not null,
  rooms int not null,
  bedrooms int not null,
  total_floors int not null,
  parking_spaces int not null,
  furnishing_type enum('unfurnished', 'semi-furnished', 'Furnished') not null,
  project_status enum('resale', 'ready to move', 'on plan', 'under construction') not null,
  amenities json not null,
  approval_status enum(
    'pending_review',
    'documents_requested',
    'under_verification',
    'compliance_hold',
    'approved',
    'rejected',
    'archived'
  ) not null default 'pending_review',
  public_status enum('hidden', 'open', 'matching', 'matched', 'archived') not null default 'hidden',
  verification_status enum(
    'unverified',
    'basic_checked',
    'documents_submitted',
    'under_review',
    'verified',
    'failed',
    'expired'
  ) not null default 'unverified',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  constraint private_availability_size_nonnegative check (size_sqft >= 0),
  constraint private_availability_price_min_nonnegative check (price_min >= 0),
  constraint private_availability_price_max_nonnegative check (price_max >= 0),
  constraint private_availability_price_order check (price_max >= price_min),
  constraint private_availability_rooms_nonnegative check (rooms >= 0),
  constraint private_availability_bedrooms_nonnegative check (bedrooms >= 0),
  constraint private_availability_total_floors_nonnegative check (total_floors >= 0),
  constraint private_availability_parking_spaces_nonnegative check (parking_spaces >= 0),
  constraint private_availability_amenities_array check (json_type(amenities) = 'ARRAY'),
  index private_availability_user_idx (user_id),
  index private_availability_status_idx (approval_status, public_status, verification_status),
  index private_availability_match_idx (country, area_city, category, offering_type, property_type, market_segment)
);

create table if not exists interest_signals (
  id char(36) primary key default (uuid()),
  user_id varchar(128) not null,
  title varchar(255) not null,
  reference_code varchar(32) not null,
  user_role enum(
    'Buyer',
    'Investor',
    'Developer',
    'agent',
    'Property manager',
    'Corporate client',
    'Admin'
  ) not null,
  availability_type enum(
    'May rent privately',
    'Upcoming vacancy',
    'May sell privately',
    'Developer inventory',
    'Land opportunity',
    'Commercial opportunity',
    'Verified listing request',
    'Private matching only'
  ) not null,
  listing_intent enum(
    'Keep private - match only',
    'Request verified private listing',
    'Request public listing after compliance approval',
    'Deal room reveal only'
  ) not null,
  market_segment enum(
    'Residential',
    'Commercial',
    'Off-plan',
    'Secondary',
    'Land',
    'Industrial',
    'Hospitality',
    'Investment',
    'Special purpose',
    'Other'
  ) not null,
  property_type enum(
    'Apartment / flat',
    'Studio apartment',
    'Serviced apartment',
    'Villa',
    'Townhouse',
    'Duplex',
    'Penthouse',
    'Mansion / luxury home',
    'Residential building',
    'Whole building / bulk units',
    'Land / development plot',
    'Residential land',
    'Commercial land',
    'Agricultural land',
    'Industrial land',
    'Mixed-use land',
    'Office',
    'Retail shop',
    'Showroom',
    'Warehouse',
    'Industrial unit',
    'Labour camp / staff accommodation',
    'Camp',
    'Commercial building',
    'Hotel / hospitality',
    'Restaurant / F&B space',
    'Clinic / medical space',
    'Farmhouse / rural property',
    'Short-term rental opportunity',
    'Off-plan unit',
    'New development unit',
    'Branded residence',
    'Investment property',
    'Other / bespoke requirement'
  ) not null,
  country varchar(100) not null,
  area_city varchar(100) not null,
  project_name varchar(255),
  building_name varchar(255),
  size_sqft decimal(12,2) not null,
  price_min decimal(15,2) not null,
  price_max decimal(15,2) not null,
  availability_date date not null,
  privacy_level enum(
    'Admin only',
    'Matched users only',
    'Deal room only',
    'Public advertising only with permit'
  ) not null,
  private_description text not null,
  category enum('residential', 'commercial') not null,
  offering_type enum('rent', 'sell') not null,
  rooms int not null,
  bedrooms int not null,
  total_floors int not null,
  parking_spaces int not null,
  furnishing_type enum('unfurnished', 'semi-furnished', 'Furnished') not null,
  project_status enum('resale', 'ready to move', 'on plan', 'under construction') not null,
  amenities json not null,
  approval_status enum(
    'pending_review',
    'documents_requested',
    'under_verification',
    'compliance_hold',
    'approved',
    'rejected',
    'archived'
  ) not null default 'pending_review',
  public_status enum('hidden', 'open', 'matching', 'matched', 'archived') not null default 'hidden',
  verification_status enum(
    'unverified',
    'basic_checked',
    'documents_submitted',
    'under_review',
    'verified',
    'failed',
    'expired'
  ) not null default 'unverified',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  constraint interest_signals_size_nonnegative check (size_sqft >= 0),
  constraint interest_signals_price_min_nonnegative check (price_min >= 0),
  constraint interest_signals_price_max_nonnegative check (price_max >= 0),
  constraint interest_signals_price_order check (price_max >= price_min),
  constraint interest_signals_rooms_nonnegative check (rooms >= 0),
  constraint interest_signals_bedrooms_nonnegative check (bedrooms >= 0),
  constraint interest_signals_total_floors_nonnegative check (total_floors >= 0),
  constraint interest_signals_parking_spaces_nonnegative check (parking_spaces >= 0),
  constraint interest_signals_amenities_array check (json_type(amenities) = 'ARRAY'),
  unique key interest_signals_reference_code_unique (reference_code),
  index interest_signals_user_idx (user_id),
  index interest_signals_status_idx (approval_status, public_status, verification_status),
  index interest_signals_match_idx (country, area_city, category, offering_type, property_type, market_segment)
);
